name: Ruby
on: [push]
jobs:
  test-and-deploy:
    uses: tedconf/github_actions_public/.github/workflows/rails.yml@main
    secrets: inherit
    with:
      cve-ignorelist: 'space-delimited list of cves to ignore (optional)'
