name: Ruby and/or Rails static analyses

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""
      bundler-version:
        description: "Bundler version to install"
        type: string
        required: false
        default: "Gemfile.lock"

jobs:
  static-analyses:
    runs-on: self-hosted
    steps:
      - uses: tedconf/setup-ruby@v1.1.4
        with:
          ssh-private-key: ${{ secrets.TEDCONF_GH_ACTIONS_JENKINS_PRIV_SSH_KEY }}
          rubygems-key: ${{ secrets.BUNDLE_RUBYGEMS__TED__COM }}
          ruby-version: ${{ inputs.ruby-version }}
          bundler-version: ${{ inputs.bundler-version }}
      - name: Update bundle-audit
        run: bundle exec bundle-audit update
      - name: Gem audit (with CVE ignorelist)
        if: inputs.cve-ignorelist != ''
        run: |
          bundle exec bundler-audit --ignore ${{ inputs.cve-ignorelist }}
      - name: Gem audit (without CVE ignorelist)
        if: inputs.cve-ignorelist == ''
        run: bundle exec bundler-audit
      - name: Check brakeman requirement
        id: brakeman
        shell: bash
        run: |
          echo "COUNT=$(grep brakeman Gemfile* | wc -l)" >> $GITHUB_OUTPUT
      - name: Scan code for vulnerabilities
        if: steps.brakeman.outputs.COUNT > 0
        run: |
          bundle exec brakeman -q -w2 --force
      - name: Run rubocop linters
        run: |
          bundle exec rubocop --parallel
