name: Ruby and/or Rails continuous integration workflow

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""
      bundler-version:
        description: "Bundler version to install"
        type: string
        required: false
        default: "Gemfile.lock"
      rake-db-tasker:
        description: 'Specify the gem to use for database tasks (to support Rails < 5)'
        type: string
        required: false
        default: "rails"
      install-ffmpeg:
        description: "Flag to install FFmpeg"
        type: boolean
        default: false
        required: false
      precompile-assets:
        description: "Precompile assets for rails app"
        type: boolean
        default: false
        required: false

jobs:
  static-analyses:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci_static_analyses.yml@v2.0.6
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist }}
      ruby-version: ${{ inputs.ruby-version }}
      bundler-version: ${{ inputs.bundler-version }}
  specs:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci_tests.yml@v2.0.6
    secrets: inherit
    with:
      ruby-version: ${{ inputs.ruby-version }}
      bundler-version: ${{ inputs.bundler-version }}
      rake-db-tasker: ${{ inputs.rake-db-tasker }}
      install-ffmpeg: ${{ inputs.install-ffmpeg }}
      precompile-assets: ${{ inputs.precompile-assets }}
