name: Rails test and deploy

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""

jobs:
  integration:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci.yml@main
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist  }}

  deployment:
    needs: integration
    uses: tedconf/github_actions_public/.github/workflows/rails_cd.yml@main
    secrets: inherit
