name: Rails test and deploy

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""

jobs:
  integrate:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci.yml@lee-test_setup_ruby_ca
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist  }}

  deploy:
    needs: test
    uses: tedconf/github_actions_public/.github/workflows/rails_cd.yml@lee-test_setup_ruby_ca
    secrets: inherit
