name: Ruby and/or Rails static analyses

on:
  workflow_call:
    inputs:
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""
      bundler-version:
        description: "Bundler version to install"
        type: string
        required: false
        default: "Gemfile.lock"
      rake-db-tasker:
        description: 'Specify the gem to use for database tasks (to support Rails < 5)'
        type: string
        required: false
        default: "rails"
      install-ffmpeg:
        description: "Flag to install FFmpeg"
        type: boolean
        default: false
        required: false
      precompile-assets:
        description: "Precompile assets for rails app"
        type: boolean
        default: false
        required: false

jobs:
  specs:
    runs-on:
      - self-hosted
    env:
      RAILS_ENV: test
      DATABASE_URL: 'mysql2://root:root@127.0.0.1' # shogo82148/actions-setup-mysql@v1 doesn't work with socket
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      REDIS_URL: 'redis://127.0.0.1'
    steps:
      - name: Runner IP address (stays up only if an error happens)
        run: curl -s 169.254.169.254/latest/meta-data/public-ipv4
      - uses: tedconf/setup-ruby@v1.1.6
        with:
          ssh-private-key: ${{ secrets.TEDCONF_GH_ACTIONS_JENKINS_PRIV_SSH_KEY }}
          rubygems-key: ${{ secrets.BUNDLE_RUBYGEMS__TED__COM }}
          contribsys-key: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
          ruby-version: ${{ inputs.ruby-version }}
          bundler-version: ${{ inputs.bundler-version }}
          rails-master-key: ${{ secrets.RAILS_MASTER_KEY }}
      - name: Check for coyote gem
        id: coyote
        shell: bash
        run: |
          echo "COUNT=$(grep coyote Gemfile* | wc -l)" >> $GITHUB_OUTPUT
      - name: Configure sysctl limits on localhost to be able to run Elasticsearch
        # Required to get Elasticsearch container to run on shgar host
        shell: bash
        if:  steps.coyote.outputs.COUNT > 0
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Setup and start Elasticsearch
        uses: tedconf/elasticsearch-github-actions@lee-self_hosted
        if: steps.coyote.output.COUNT > 0
        with:
          stack-version: 6.8.23
          plugins: 'analysis-icu analysis-phonetic'

      - name: Elasticsearch is reachable
        if: steps.coyote.outputs.COUNT > 0
        run: |
          curl --verbose --show-error http://localhost:9200
      - name: Check if database is needed
        id: uses_db
        shell: bash
        run: |
          has_db_yml=0
          if [ -f "./config/database.yml" ]; then
            has_db_yml=1
          fi
          echo "USES_DB=$has_db_yml" >> $GITHUB_OUTPUT
      - name: Check for Redis dependency
        if: steps.uses_db.outputs.USES_DB > 0
        uses: tedconf/install-ruby-dependency-action@v1.1.3
        with:
          gem-name: redis
          required-library: "redis-tools redis-server"
      - name: Check if redis is required
        id: redis
        shell: bash
        run: |
          echo "COUNT=$(grep redis Gemfile* | wc -l)" >> $GITHUB_OUTPUT
      - name: Wait for Redis
        if: steps.redis.outputs.COUNT > 0
        run: |
          redis-cli ping
      - name: Check if it uses the older secrets.yml for secrets.
        id: has_secrets
        shell: bash
        run: |
          has_secrets_yml=0
          if [ -f "./config/secrets.github.yml" ]; then
            has_secrets_yml=1
          fi
          echo "HAS_SECRETS=$has_secrets_yml" >> $GITHUB_OUTPUT
      - name: Set up test secrets
        if: steps.uses_db.outputs.USES_DB > 0 && steps.has_secrets.outputs.HAS_SECRETS > 0
        run: cp config/secrets.github.yml config/secrets.yml
      - name: Setup MySQL
        # Workaround for MySQL in ACT until
        # https://bugs.launchpad.net/ubuntu/focal/+source/mysql-8.0/+bug/1899248 is
        # released
        if: steps.uses_db.outputs.USES_DB > 0 && env.ACT
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
          root-password: root
      - name: Start MySQL
        if: ${{ steps.uses_db.outputs.USES_DB > 0 && !env.ACT }}
        run: sudo /etc/init.d/mysql start
      - name: Create DB
        if: steps.uses_db.outputs.USES_DB > 0
        env:
          RAILS_ENV: test
        run: |
          bundle exec ${{ inputs.rake-db-tasker }} db:create
          bundle exec ${{ inputs.rake-db-tasker }} db:schema:load
      - name: Install FFmpeg
        shell: bash
        if: inputs.install-ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo ln -sf $(which ffprobe) /usr/local/bin/ffprobe
          sudo ln -sf $(which ffmpeg) /usr/local/bin/ffmpeg
      - name: Install yarn
        if: inputs.precompile-assets
        run: |
          sudo npm install --global yarn
      - name: Precompile assets
        if: inputs.precompile-assets
        shell: bash
        run:
          bundle exec rails assets:precompile
      - name: Run tests
        run: |
          bundle exec rspec
      # prevent accidentally leaking secrets
      - name: Remove test secrets
        if: steps.uses_db.outputs.USES_DB > 0 && steps.has_secrets.outputs.HAS_SECRETS > 0
        run: |
          rm config/secrets.yml
