name: Rails test and deploy

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""
      bundler-version:
        description: "Override to specify bundler version to use"
        # Acceptable values: https://github.com/ruby/setup-ruby/blob/master/action.yml#L19
        type: string
        required: false
        default: "Gemfile.lock"

jobs:
  integration:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci.yml@v2.0.2
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist  }}
      ruby-version: ${{ inputs.ruby-version }}
      bundler-version: ${{ inputs.bundler-version }}

  deployment:
    needs: integration
    uses: tedconf/github_actions_public/.github/workflows/rails_cd.yml@v2.0.2
    secrets: inherit
