name: Rails test and deploy

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""
      bundler-version:
        description: "Override to specify bundler version to use"
        # Acceptable values: https://github.com/ruby/setup-ruby/blob/master/action.yml#L19
        type: string
        required: false
        default: "Gemfile.lock"
      rake-db-tasker:
        description: 'Specify the gem to use for database tasks (to support Rails < 5)'
        type: string
        required: false
        default: "rails"
      install-ffmpeg:
        description: "Flag to install FFmpeg"
        default: false
        required: false

jobs:
  integration:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci.yml@v2.0.6
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist  }}
      ruby-version: ${{ inputs.ruby-version }}
      bundler-version: ${{ inputs.bundler-version }}
      rake-db-tasker: ${{ inputs.rake-db-tasker }}
      install-ffmpeg: ${{ inputs.install-ffmpeg }}

  deployment:
    needs: integration
    uses: tedconf/github_actions_public/.github/workflows/rails_cd.yml@v2.0.6
    secrets: inherit
