name: Ruby and/or Rails continuous integration workflow

on:
  workflow_call:
    inputs:
      cve-ignorelist:
        description: "space-delimited string of CVEs to ignore"
        type: string
        required: false
        default: ""
      ruby-version:
        description: "Ruby version to install"
        type: string
        required: false
        default: ""

jobs:
  static-analyses:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci_static_analyses.yml@v2.0.1
    secrets: inherit
    with:
      cve-ignorelist: ${{ inputs.cve-ignorelist }}
      ruby-version: ${{ inputs.ruby-version }}
  specs:
    uses: tedconf/github_actions_public/.github/workflows/rails_ci_tests.yml@v2.0.1
    secrets: inherit
    with:
      ruby-version: ${{ inputs.ruby-version }}
